#FROM adoptopenjdk:17-jdk-hotspot AS builder
RUN pwd
RUN cp /var/jenkins_home/workspace/application.yml src/main/resources/application.yml
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN chmod +x ./gradlew
RUN ./gradlew build

#FROM adoptopenjdk:11-jdk-hotspot
#COPY --from=builder build/libs/*.jar app.jar
COPY build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "/app.jar" ]