# docker-compose.yml
#https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.8'
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: moogle-redis
    hostname: moogle-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    restart: always